### ISSUE TITLE
handle forms on submit

### ISSUE THREAD

**Issue by queckezz** [vdux/vdux#4]
Im still confused on how to handle forms. Let's say I have a simple form

``` js
// action creator
const inc = () => {
  const amount = readValueSomehow() || 1 // read value from `input`?

  return {
    type: 'INCREMENT' ,
    payload: { amount }
  }
}

// view
const form = props => h('div', [
  h('form' , { 'ev-submit': inc }, [
    h('input', { type: 'text' }),
    h('button', 'Increment')
  ]),

  h('span', props.counter)
])
```

How do I go about reading a value from a different form ìnput? In React there's a thing called `ref` where you imperatively get the nodes value: 

``` js
// node
<input ref="myInput" />
// get it with
this.refs.myInput
```

Another thing that comes to my mind is using something like [form-serialize](https://github.com/dominicbarnes/form-serialize):

``` js
// action creator
const inc = ({ target, preventDefault }) => {
  preventDefault()
  const data = serialize(target)
  // ...
}
```

But both of them seem kind of a hack because you are accessing raw DOM nodes. Im sure I'm missing something obvious here.

**Comment by queckezz** [comment]
I'm overthinking here and the `form-serialize` or native `new FormData()` approach might just be good enough.

Sorry for the noise.

**Comment by ashaffer** [comment]
It's funny I went through the same thought process at first.  I also wrote a clone of form-serialize that works with npm btw if you are having trouble with that: https://github.com/ashaffer/form-serialize

But ya I think in general its ok to access values from raw DOM nodes, because they are being passed in to you.  It's just not ok to mutate them.  The other approach you could take is putting `ev-change` handlers on all of the elements and maintaining their state yourself, which is appropriate for certain things, but you'll just have to decide that on a case-by-case basis.
